import type { Coach } from '@/types';

export const COACHES: Coach[] = [
  {
    id: 'coach-animesh-ray',
    name: 'Animesh Ray',
    title: 'FIDE Development Instructor (DI)',
    fideId: '33391718',
    specialization: 'Beginner to Advanced Training & Tournament Prep',
    experience: 'FIDE Certified DI Trainer',
    students: 180,
    country: 'India',
    flag: '🇮🇳',
    imageUrl: '/coaches/animesh-ray.jpg',

    bio: "Animesh Ray is a FIDE-certified Development Instructor dedicated to helping players build strong fundamentals, improve tactical vision, and gain confidence in tournament play. His coaching focuses on structured learning, practical exercises, and personalized improvement plans. His DI title is listed by the FIDE Trainers' Commission.",
    achievements: [
      'FIDE Development Instructor (DI)',
      'FIDE ID: 33391718 (Recognized by FIDE)',
      'Languages: English, Hindi, Odia',
      'Tactical & Tournament Prep Specialist',
    ],
    languages: ['English', 'Hindi', 'Odia'],
    coachingMode: 'Online • 1-on-1 • Group Classes',
  },

  {
    id: 'coach-manoj-kumar-rai',
    name: 'Manoj Kumar Rai',
    title: 'FIDE National Instructor (NI)',
    fideRating: 1850,
    fideId: '35017217',
    specialization: 'Chess Fundamentals & Positional Strategy',
    experience: 'FIDE Certified NI Trainer',
    students: 150,
    country: 'India',
    flag: '🇮🇳',
    imageUrl: '/coaches/manoj-kumar-rai.jpg',

    bio: "Manoj Kumar Rai is a FIDE-certified National Instructor who provides structured chess coaching for developing players. His training emphasizes sound fundamentals, strategic understanding, and competitive preparation. His NI title is recognized by the FIDE Trainers' Commission.",
    achievements: [
      'FIDE National Instructor (NI)',
      'FIDE ID: 35017217 (Recognized by FIDE)',
      'Positional Chess & Endgame Training',
      'Student Improvement Program Specialist',
    ],
    languages: ['English', 'Hindi'],
    coachingMode: 'Online • 1-on-1 • Group Classes',
  },
  {
    id: 'coach-ayush-pattanaik',
    name: 'Ayush Pattanaik',
    title: 'FIDE National Instructor (NI)',
    fideRating: 1891,
    fideId: '25014870',
    specialization: 'Intermediate & Advanced Opening/Calculation',
    experience: 'FIDE Certified NI Trainer',
    students: 130,
    country: 'India',
    flag: '🇮🇳',
    imageUrl: '/coaches/ayush-pattanaik.jpg',

    bio: 'Ayush Pattanaik is a FIDE National Instructor with a peak rating of 1891 (Rapid 1860). He specializes in training intermediate and advanced players through deep calculation drills, opening preparation, and tournament strategy. Supported by his official FIDE profile.',
    achievements: [
      'FIDE National Instructor (NI)',
      'FIDE ID: 25014870 (Peak Rating 1891)',
      'Rapid Rating: 1860',
      'Calculation & Opening Preparation Expert',
    ],
    languages: ['English', 'Hindi', 'Odia'],
    coachingMode: 'Online • 1-on-1 • Group Classes',
  },
  {
    id: 'coach-pradipta-patnaik',
    name: 'Pradipta Patnaik',
    title: 'Academy Chess Coach (~1750 Elo)',
    fideRating: 1750,
    specialization: 'Beginner Coaching & Tactical Fundamentals',
    experience: 'Senior Academy Coach',
    students: 110,
    country: 'India',
    flag: '🇮🇳',
    imageUrl:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&q=80',
    bio: 'Pradipta Patnaik is an academy coach focused on building strong chess fundamentals for beginners and intermediate players. His coaching emphasizes tactical awareness, calculation, and practical game improvement.',
    achievements: [
      'Academy Chess Coach (~1750 Elo)',
      'Kids & Beginner Training Specialist',
      'Tactical Awareness & Calculation Expert',
      'Online & Offline Coaching Modes',
    ],
    languages: ['English', 'Hindi', 'Odia'],
    coachingMode: 'Online • Offline',
  },
];
