import type { Program } from '@/types';

export const PROGRAMS: Program[] = [
  {
    id: 'beginner',
    title: 'Beginner Foundation',
    subtitle: 'Start Your Chess Journey',
    level: 'Beginner',
    ageRange: '6–10 years',
    duration: '3 months',
    sessionsPerWeek: 2,
    sessionDuration: '45 min',
    price: 'From $49/month',
    featured: false,
    color: 'blue',
    description:
      'The perfect introduction to chess for young learners. Students master all the rules, piece movements, basic tactics, and develop a love for the game through engaging, structured lessons.',
    features: [
      'Piece movements & rules',
      'Board awareness',
      'Basic tactics (fork, pin)',
      'Checkmate patterns',
      'Interactive puzzles',
      'FIDE-rated coach',
      'Progress tracking',
      'Certificate upon completion',
    ],
  },
  {
    id: 'intermediate',
    title: 'Intermediate Mastery',
    subtitle: 'Sharpen Your Tactical Skills',
    level: 'Intermediate',
    ageRange: '10–14 years',
    duration: '6 months',
    sessionsPerWeek: 3,
    sessionDuration: '60 min',
    price: 'From $79/month',
    featured: true,
    color: 'gold',
    description:
      'Build on your foundation and develop powerful tactical patterns, opening knowledge, and strategic thinking. This program is designed to take club players to the next level of competitive play.',
    features: [
      'Opening theory (e4, d4, Sicilian)',
      'Tactical motifs (20+ patterns)',
      'Endgame fundamentals',
      'Game analysis sessions',
      'Lichess study integration',
      'Weekly homework assignments',
      'Monthly tournaments',
      'FIDE rating support',
    ],
  },
  {
    id: 'advanced',
    title: 'Advanced Excellence',
    subtitle: 'Compete at the Highest Level',
    level: 'Advanced',
    ageRange: '12–16 years',
    duration: '12 months',
    sessionsPerWeek: 4,
    sessionDuration: '90 min',
    price: 'From $129/month',
    featured: false,
    color: 'blue',
    description:
      'An intensive program for serious players with FIDE ratings. Deep opening preparation, strategic planning, complex endgames, and personalized coaching from titled players.',
    features: [
      'Deep opening repertoire',
      'Positional chess & pawn structures',
      'Complex endgame theory',
      'Database analysis (Lichess)',
      'Titled player coaching',
      'Game preparation sessions',
      'International tournament guidance',
      'Personal training plan',
    ],
  },
  {
    id: 'tournament',
    title: 'Tournament Preparation',
    subtitle: 'Win Medals, Build Legacy',
    level: 'Tournament',
    ageRange: '10–18 years',
    duration: 'Ongoing',
    sessionsPerWeek: 5,
    sessionDuration: '90 min',
    price: 'From $199/month',
    featured: false,
    color: 'blue',
    description:
      'Elite preparation for national and international competitions. Compete in FIDE-rated events, receive dedicated coaching for tournament cycles, and build a championship-level game.',
    features: [
      'Tournament-specific preparation',
      'Opponent analysis',
      'Mental fitness coaching',
      'Time management training',
      'Live tournament support',
      'Post-game debriefs',
      'FIDE rating management',
      'National team pathway',
    ],
  },
];
