import type { StudentBotProfile, BotGameRecord } from './types';

export type AchievementCategory =
  | 'milestones'
  | 'tiers'
  | 'pieces'
  | 'puzzles'
  | 'openings'
  | 'secret';

export type AchievementRarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface AchievementContext {
  profile: StudentBotProfile | null;
  recentGames: BotGameRecord[];
  quizScore: number;
  streakCount: number;
  adventureHistory: string[];
  puzzlesSolvedCount: number;
}

export interface TrophyAchievement {
  id: string;
  category: AchievementCategory;
  title: string;
  icon: string;
  desc: string;
  rarity: AchievementRarity;
  xpReward: number;
  checkUnlocked: (ctx: AchievementContext) => boolean;
}

export const TROPHY_ACHIEVEMENTS: TrophyAchievement[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 1. MILESTONES & RATING PROGRESSION 🏆 (20 Achievements)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'm-first-blood',
    category: 'milestones',
    title: 'First Blood',
    icon: '🩸',
    desc: 'Win your first match against any academy bot',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => (ctx.profile?.wins ?? 0) >= 1 || ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'm-5-wins',
    category: 'milestones',
    title: 'Rising Cadet',
    icon: '⚔️',
    desc: 'Achieve 5 victorious bot victories',
    rarity: 'common',
    xpReward: 50,
    checkUnlocked: (ctx) => (ctx.profile?.wins ?? 0) >= 5 || ctx.recentGames.filter((g) => g.result === 'win').length >= 5,
  },
  {
    id: 'm-10-wins',
    category: 'milestones',
    title: 'Tactical Fighter',
    icon: '🛡️',
    desc: 'Win 10 matches across any bot levels',
    rarity: 'rare',
    xpReward: 75,
    checkUnlocked: (ctx) => (ctx.profile?.wins ?? 0) >= 10 || ctx.recentGames.filter((g) => g.result === 'win').length >= 10,
  },
  {
    id: 'm-25-wins',
    category: 'milestones',
    title: 'Arena Gladiator',
    icon: '🗡️',
    desc: 'Accumulate 25 bot victories in the arena',
    rarity: 'rare',
    xpReward: 120,
    checkUnlocked: (ctx) => (ctx.profile?.wins ?? 0) >= 25,
  },
  {
    id: 'm-50-wins',
    category: 'milestones',
    title: 'Centurion of Chess',
    icon: '🎖️',
    desc: 'Win 50 bot games in total',
    rarity: 'epic',
    xpReward: 250,
    checkUnlocked: (ctx) => (ctx.profile?.wins ?? 0) >= 50,
  },
  {
    id: 'm-100-wins',
    category: 'milestones',
    title: 'Century Master',
    icon: '👑',
    desc: 'Reach an astounding 100 victories against academy bots',
    rarity: 'legendary',
    xpReward: 500,
    checkUnlocked: (ctx) => (ctx.profile?.wins ?? 0) >= 100,
  },
  {
    id: 'm-games-10',
    category: 'milestones',
    title: 'Game Initiate',
    icon: '🎮',
    desc: 'Complete 10 total bot games win, loss, or draw',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 10 || ctx.recentGames.length >= 10,
  },
  {
    id: 'm-games-50',
    category: 'milestones',
    title: 'Persistent Fighter',
    icon: '⏳',
    desc: 'Play 50 total games in your training journey',
    rarity: 'rare',
    xpReward: 100,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 50,
  },
  {
    id: 'm-games-100',
    category: 'milestones',
    title: 'Iron Will',
    icon: '🦾',
    desc: 'Log 100 full matches in the Bot Arena',
    rarity: 'epic',
    xpReward: 200,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 100,
  },
  {
    id: 'm-rating-500',
    category: 'milestones',
    title: 'Rating 500+',
    icon: '🌱',
    desc: 'Climb past 500 Student Arena Rating',
    rarity: 'common',
    xpReward: 40,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 500,
  },
  {
    id: 'm-rating-600',
    category: 'milestones',
    title: 'Rating 600+',
    icon: '🌿',
    desc: 'Cross 600 Student Arena Rating',
    rarity: 'common',
    xpReward: 50,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 600,
  },
  {
    id: 'm-rating-700',
    category: 'milestones',
    title: 'Rating 700+',
    icon: '🥉',
    desc: 'Achieve 700 Student Arena Rating',
    rarity: 'rare',
    xpReward: 60,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 700,
  },
  {
    id: 'm-rating-800',
    category: 'milestones',
    title: 'Rating 800+',
    icon: '🥈',
    desc: 'Break through the 800 rating barrier',
    rarity: 'rare',
    xpReward: 80,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 800,
  },
  {
    id: 'm-rating-900',
    category: 'milestones',
    title: 'Rating 900+',
    icon: '🥇',
    desc: 'Reach 900 Student Arena Rating',
    rarity: 'rare',
    xpReward: 100,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 900,
  },
  {
    id: 'm-rating-1000',
    category: 'milestones',
    title: 'Grandmaster Prodigy (1000+)',
    icon: '💎',
    desc: 'Enter the 4-digit elite with a 1000+ rating',
    rarity: 'epic',
    xpReward: 200,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 1000,
  },
  {
    id: 'm-rating-1200',
    category: 'milestones',
    title: 'Club Champion (1200+)',
    icon: '🏆',
    desc: 'Reach 1200 Student Arena Rating',
    rarity: 'epic',
    xpReward: 300,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 1200,
  },
  {
    id: 'm-rating-1400',
    category: 'milestones',
    title: 'Tournament Contender (1400+)',
    icon: '🏅',
    desc: 'Cross 1400 Student Arena Rating',
    rarity: 'legendary',
    xpReward: 400,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 1400,
  },
  {
    id: 'm-rating-1600',
    category: 'milestones',
    title: 'FIDE Candidate (1600+)',
    icon: '🌟',
    desc: 'Achieve 1600 Student Arena Rating',
    rarity: 'legendary',
    xpReward: 600,
    checkUnlocked: (ctx) => (ctx.profile?.rating ?? 400) >= 1600,
  },
  {
    id: 'm-points-500',
    category: 'milestones',
    title: 'Point Gatherer',
    icon: '💰',
    desc: 'Earn 500 total Academy Training Points',
    rarity: 'common',
    xpReward: 50,
    checkUnlocked: (ctx) => (ctx.profile?.training_points ?? 0) >= 500,
  },
  {
    id: 'm-points-2000',
    category: 'milestones',
    title: 'Point Tycoon',
    icon: '💎',
    desc: 'Amass 2,000 Academy Training Points',
    rarity: 'epic',
    xpReward: 250,
    checkUnlocked: (ctx) => (ctx.profile?.training_points ?? 0) >= 2000,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. BOT TIERS & BOSS BATTLES 🥇 (15 Achievements)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'tier-lvl-1',
    category: 'tiers',
    title: 'Pawn Crusher',
    icon: '♟️',
    desc: 'Defeat Level 1 Bot (400 ELO)',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 1),
  },
  {
    id: 'tier-lvl-2',
    category: 'tiers',
    title: 'Knight Tamer',
    icon: '♞',
    desc: 'Defeat Level 2 Bot (600 ELO)',
    rarity: 'common',
    xpReward: 35,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 2),
  },
  {
    id: 'tier-lvl-3',
    category: 'tiers',
    title: 'Bishop Duelist',
    icon: '♝',
    desc: 'Defeat Level 3 Bot (800 ELO)',
    rarity: 'common',
    xpReward: 45,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 3),
  },
  {
    id: 'tier-bronze-all',
    category: 'tiers',
    title: 'Bronze Conqueror',
    icon: '🥉',
    desc: 'Conquer all Bronze Tiers (Levels 1, 2, and 3)',
    rarity: 'rare',
    xpReward: 80,
    checkUnlocked: (ctx) => {
      const levels = new Set(ctx.recentGames.filter((g) => g.result === 'win').map((g) => g.bot_level));
      return levels.has(1) && levels.has(2) && levels.has(3);
    },
  },
  {
    id: 'tier-lvl-4',
    category: 'tiers',
    title: 'Rook Breaker',
    icon: '♜',
    desc: 'Defeat Level 4 Bot (1000 ELO)',
    rarity: 'rare',
    xpReward: 60,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 4),
  },
  {
    id: 'tier-lvl-5',
    category: 'tiers',
    title: 'Tactical Striker',
    icon: '🎯',
    desc: 'Defeat Level 5 Bot (1200 ELO)',
    rarity: 'rare',
    xpReward: 80,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 5),
  },
  {
    id: 'tier-lvl-6',
    category: 'tiers',
    title: 'Queen Challenger',
    icon: '♛',
    desc: 'Defeat Level 6 Bot (1400 ELO)',
    rarity: 'rare',
    xpReward: 100,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 6),
  },
  {
    id: 'tier-silver-all',
    category: 'tiers',
    title: 'Silver Master',
    icon: '🥈',
    desc: 'Defeat Levels 4, 5, and 6 Bots',
    rarity: 'epic',
    xpReward: 180,
    checkUnlocked: (ctx) => {
      const levels = new Set(ctx.recentGames.filter((g) => g.result === 'win').map((g) => g.bot_level));
      return levels.has(4) && levels.has(5) && levels.has(6);
    },
  },
  {
    id: 'tier-lvl-7',
    category: 'tiers',
    title: 'National Master Slayer',
    icon: '🎖️',
    desc: 'Defeat Level 7 Master Bot (1600 ELO)',
    rarity: 'epic',
    xpReward: 150,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 7),
  },
  {
    id: 'tier-lvl-8',
    category: 'tiers',
    title: 'IM Subduer',
    icon: '🔥',
    desc: 'Defeat Level 8 International Master Bot (1800 ELO)',
    rarity: 'epic',
    xpReward: 200,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 8),
  },
  {
    id: 'tier-gold-all',
    category: 'tiers',
    title: 'Gold Champion',
    icon: '🥇',
    desc: 'Defeat both Level 7 and Level 8 Master Bots',
    rarity: 'legendary',
    xpReward: 300,
    checkUnlocked: (ctx) => {
      const levels = new Set(ctx.recentGames.filter((g) => g.result === 'win').map((g) => g.bot_level));
      return levels.has(7) && levels.has(8);
    },
  },
  {
    id: 'tier-lvl-9',
    category: 'tiers',
    title: 'Super GM Vanquisher',
    icon: '👑',
    desc: 'Defeat Level 9 Super GM Bot (2000 ELO)',
    rarity: 'legendary',
    xpReward: 400,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 9),
  },
  {
    id: 'tier-lvl-10',
    category: 'tiers',
    title: 'Engine Destroyer',
    icon: '⚡',
    desc: 'Defeat Level 10 Maximum Engine (2200 ELO)',
    rarity: 'legendary',
    xpReward: 600,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win' && g.bot_level === 10),
  },
  {
    id: 'tier-diamond-all',
    category: 'tiers',
    title: 'Diamond Virtuoso',
    icon: '💎',
    desc: 'Win against both Super GM and Engine bots',
    rarity: 'legendary',
    xpReward: 800,
    checkUnlocked: (ctx) => {
      const levels = new Set(ctx.recentGames.filter((g) => g.result === 'win').map((g) => g.bot_level));
      return levels.has(9) && levels.has(10);
    },
  },
  {
    id: 'tier-boss-hp',
    category: 'tiers',
    title: 'Boss Slayer',
    icon: '⚔️',
    desc: 'Deplete a Bot HP bar in Boss Battle Combat Mode',
    rarity: 'rare',
    xpReward: 75,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. PIECE MASTERY & TACTICAL MOTIFS ♞ (20 Achievements)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'piece-pawn-pusher',
    category: 'pieces',
    title: 'Pawn Stormer',
    icon: '♟️',
    desc: 'Play 3 or more bot training matches with active pawn play',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 3 || ctx.recentGames.length >= 3,
  },
  {
    id: 'piece-knight-fork',
    category: 'pieces',
    title: 'Royal Forker',
    icon: '♞',
    desc: 'Master the Royal Knight Fork tactical motif',
    rarity: 'common',
    xpReward: 35,
    checkUnlocked: (ctx) => ctx.quizScore >= 3,
  },
  {
    id: 'piece-bishop-pin',
    category: 'pieces',
    title: 'Pin Architect',
    icon: '♝',
    desc: 'Execute pinning pressure on long diagonals',
    rarity: 'common',
    xpReward: 35,
    checkUnlocked: (ctx) => ctx.quizScore >= 4,
  },
  {
    id: 'piece-rook-battery',
    category: 'pieces',
    title: 'Rook Battery',
    icon: '♜',
    desc: 'Seize open files and control the 7th rank',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.quizScore >= 5,
  },
  {
    id: 'piece-queen-dominance',
    category: 'pieces',
    title: 'Queen Majesty',
    icon: '♛',
    desc: 'Win a game using active Queen combinations',
    rarity: 'rare',
    xpReward: 60,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'piece-king-safety',
    category: 'pieces',
    title: 'Castling Fortress',
    icon: '🏰',
    desc: 'Safeguard your King with timely castling in bot matches',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.recentGames.length >= 1,
  },
  {
    id: 'piece-absolute-pin',
    category: 'pieces',
    title: 'Absolute Immobilizer',
    icon: '📌',
    desc: 'Answer the Absolute Pin Quest accurately',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.quizScore >= 3,
  },
  {
    id: 'piece-smothered-mate',
    category: 'pieces',
    title: 'Smothered Sorcerer',
    icon: '🐴',
    desc: 'Solve the famous Philidor Smothered Mate pattern',
    rarity: 'rare',
    xpReward: 60,
    checkUnlocked: (ctx) => ctx.quizScore >= 8,
  },
  {
    id: 'piece-greek-gift',
    category: 'pieces',
    title: 'Greek Gift Specialist',
    icon: '🎁',
    desc: 'Execute the classic Bxh7+ sacrifice sequence',
    rarity: 'epic',
    xpReward: 75,
    checkUnlocked: (ctx) => ctx.quizScore >= 6,
  },
  {
    id: 'piece-windmill',
    category: 'pieces',
    title: 'Windmill Dynamo',
    icon: '🔄',
    desc: 'Execute alternating direct and discovered checks',
    rarity: 'epic',
    xpReward: 80,
    checkUnlocked: (ctx) => ctx.quizScore >= 10,
  },
  {
    id: 'piece-en-passant',
    category: 'pieces',
    title: 'En Passant Wizard',
    icon: '⚡',
    desc: 'Capture in-passing on the immediate reply',
    rarity: 'rare',
    xpReward: 40,
    checkUnlocked: (ctx) => ctx.quizScore >= 9,
  },
  {
    id: 'piece-back-rank',
    category: 'pieces',
    title: 'Back-Rank Executioner',
    icon: '🪟',
    desc: 'Deliver or defend against back-rank checkmate threats',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.quizScore >= 5,
  },
  {
    id: 'piece-remove-defender',
    category: 'pieces',
    title: 'Defender Demolisher',
    icon: '🎯',
    desc: 'Eliminate or deflect a guarding piece for free material',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.quizScore >= 7,
  },
  {
    id: 'piece-skewer',
    category: 'pieces',
    title: 'Skewer Impaler',
    icon: '🍢',
    desc: 'Attack a valuable piece to win the target behind it',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.quizScore >= 4,
  },
  {
    id: 'piece-double-check',
    category: 'pieces',
    title: 'Double Check Thunder',
    icon: '⚡',
    desc: 'Deliver simultaneous checks from two different pieces',
    rarity: 'epic',
    xpReward: 70,
    checkUnlocked: (ctx) => ctx.quizScore >= 6,
  },
  {
    id: 'piece-discovered-attack',
    category: 'pieces',
    title: 'Discovered Blade',
    icon: '🗡️',
    desc: 'Unmask a hidden attacking ray by moving an obstacle',
    rarity: 'rare',
    xpReward: 45,
    checkUnlocked: (ctx) => ctx.quizScore >= 5,
  },
  {
    id: 'piece-deflection',
    category: 'pieces',
    title: 'Deflection Artist',
    icon: '🪃',
    desc: 'Force an enemy piece away from its critical defensive post',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.quizScore >= 7,
  },
  {
    id: 'piece-decoy',
    category: 'pieces',
    title: 'Decoy Mastermind',
    icon: '🪤',
    desc: 'Lure an enemy king or queen onto a doomed square',
    rarity: 'epic',
    xpReward: 65,
    checkUnlocked: (ctx) => ctx.quizScore >= 8,
  },
  {
    id: 'piece-clearance',
    category: 'pieces',
    title: 'Clearance Pioneer',
    icon: '🧹',
    desc: 'Vacate a crucial square or file for an attacking teammate',
    rarity: 'epic',
    xpReward: 70,
    checkUnlocked: (ctx) => ctx.quizScore >= 6,
  },
  {
    id: 'piece-x-ray',
    category: 'pieces',
    title: 'X-Ray Visionary',
    icon: '👁️',
    desc: 'Attack or defend through an opposing piece',
    rarity: 'epic',
    xpReward: 75,
    checkUnlocked: (ctx) => ctx.quizScore >= 9,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. TACTICAL QUESTS & PUZZLES 🧩 (16 Achievements)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'q-novice',
    category: 'puzzles',
    title: 'Quest Initiate',
    icon: '🧩',
    desc: 'Solve your first Interactive Tactical Quest',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 1,
  },
  {
    id: 'q-scholar',
    category: 'puzzles',
    title: 'Scholar’s Shield',
    icon: '🛡️',
    desc: 'Successfully shut down the 4-move checkmate in Quest 1',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 1,
  },
  {
    id: 'q-fried-liver',
    category: 'puzzles',
    title: 'Fried Liver Savvy',
    icon: '🔥',
    desc: 'Master the Italian Game trap in Quest 2',
    rarity: 'rare',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.quizScore >= 2,
  },
  {
    id: 'q-pin-expert',
    category: 'puzzles',
    title: 'Pin Authority',
    icon: '📌',
    desc: 'Understand absolute vs relative pins in Quest 3',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 3,
  },
  {
    id: 'q-fork-ace',
    category: 'puzzles',
    title: 'Fork Ace',
    icon: '🍴',
    desc: 'Solve the royal knight fork in Quest 4',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 4,
  },
  {
    id: 'q-luft',
    category: 'puzzles',
    title: 'Breathing Room',
    icon: '🪟',
    desc: 'Master King safety and the Luft escape in Quest 5',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 5,
  },
  {
    id: 'q-greek-gift-q',
    category: 'puzzles',
    title: 'Greek Gift Solver',
    icon: '🎁',
    desc: 'Unravel the Bxh7+ attacking plan in Quest 6',
    rarity: 'rare',
    xpReward: 35,
    checkUnlocked: (ctx) => ctx.quizScore >= 6,
  },
  {
    id: 'q-defender-q',
    category: 'puzzles',
    title: 'Guardian Breaker',
    icon: '🎯',
    desc: 'Solve the removing the defender challenge in Quest 7',
    rarity: 'rare',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.quizScore >= 7,
  },
  {
    id: 'q-smothered-q',
    category: 'puzzles',
    title: 'Smothered Prodigy',
    icon: '🐴',
    desc: 'Deliver the smothered knight mate in Quest 8',
    rarity: 'rare',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.quizScore >= 8,
  },
  {
    id: 'q-en-passant-q',
    category: 'puzzles',
    title: 'En Passant Striker',
    icon: '♟️',
    desc: 'Execute the diagonal pawn strike in Quest 9',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 9,
  },
  {
    id: 'q-windmill-q',
    category: 'puzzles',
    title: 'Windmill Conqueror',
    icon: '🔄',
    desc: 'Master the alternating see-saw attack in Quest 10',
    rarity: 'rare',
    xpReward: 35,
    checkUnlocked: (ctx) => ctx.quizScore >= 10,
  },
  {
    id: 'q-perfect-10',
    category: 'puzzles',
    title: 'Tactical Perfectionist',
    icon: '🏆',
    desc: 'Solve all 10 Tactical Quests for a perfect 10/10 score',
    rarity: 'legendary',
    xpReward: 250,
    checkUnlocked: (ctx) => ctx.quizScore >= 10,
  },
  {
    id: 'puz-10-solved',
    category: 'puzzles',
    title: 'Puzzle Apprentice',
    icon: '🧩',
    desc: 'Solve 10 personalized weakness puzzles',
    rarity: 'common',
    xpReward: 40,
    checkUnlocked: (ctx) => (ctx.profile?.puzzles_solved ?? 0) >= 10 || ctx.puzzlesSolvedCount >= 10,
  },
  {
    id: 'puz-25-solved',
    category: 'puzzles',
    title: 'Puzzle Enthusiast',
    icon: '🔍',
    desc: 'Solve 25 personalized puzzles',
    rarity: 'rare',
    xpReward: 80,
    checkUnlocked: (ctx) => (ctx.profile?.puzzles_solved ?? 0) >= 25 || ctx.puzzlesSolvedCount >= 25,
  },
  {
    id: 'puz-50-solved',
    category: 'puzzles',
    title: 'Tactical Dynamo',
    icon: '⚡',
    desc: 'Solve 50 puzzles from the academy puzzle bank',
    rarity: 'epic',
    xpReward: 150,
    checkUnlocked: (ctx) => (ctx.profile?.puzzles_solved ?? 0) >= 50 || ctx.puzzlesSolvedCount >= 50,
  },
  {
    id: 'puz-100-solved',
    category: 'puzzles',
    title: 'Puzzle Grandmaster',
    icon: '💎',
    desc: 'Crack 100 tactical puzzles across all categories',
    rarity: 'legendary',
    xpReward: 350,
    checkUnlocked: (ctx) => (ctx.profile?.puzzles_solved ?? 0) >= 100 || ctx.puzzlesSolvedCount >= 100,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. OPENINGS & REPERTOIRE 📖 (14 Achievements)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'op-italian-explorer',
    category: 'openings',
    title: 'Italian Explorer',
    icon: '🇮🇹',
    desc: 'Explore the Italian Game opening tree branches',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.adventureHistory.length >= 2,
  },
  {
    id: 'op-fried-liver-tree',
    category: 'openings',
    title: 'Fried Liver Defier',
    icon: '🛡️',
    desc: 'Navigate 3 or more nodes in the Fried Liver Adventure',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.adventureHistory.length >= 3,
  },
  {
    id: 'op-adventure-finisher',
    category: 'openings',
    title: 'Opening Cartographer',
    icon: '🗺️',
    desc: 'Reach the conclusion of an Opening Tree Adventure',
    rarity: 'epic',
    xpReward: 100,
    checkUnlocked: (ctx) => ctx.adventureHistory.length >= 5,
  },
  {
    id: 'op-sicilian-warrior',
    category: 'openings',
    title: 'Sicilian Warrior',
    icon: '⚔️',
    desc: 'Engage in sharp 1... c5 Sicilian Defense battles',
    rarity: 'rare',
    xpReward: 40,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 2,
  },
  {
    id: 'op-french-defender',
    category: 'openings',
    title: 'French Fortress',
    icon: '🏰',
    desc: 'Battle through closed French Defense structures',
    rarity: 'rare',
    xpReward: 40,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 4,
  },
  {
    id: 'op-caro-kann-wall',
    category: 'openings',
    title: 'Caro-Kann Pillar',
    icon: '🗿',
    desc: 'Demonstrate solid pawn chains in 1... c6 structures',
    rarity: 'rare',
    xpReward: 40,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 6,
  },
  {
    id: 'op-ruy-lopez',
    category: 'openings',
    title: 'Spanish Archduke',
    icon: '🇪🇸',
    desc: 'Explore deep Ruy Lopez strategic lines',
    rarity: 'epic',
    xpReward: 60,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 8,
  },
  {
    id: 'op-queens-gambit',
    category: 'openings',
    title: 'Queen’s Gambiteer',
    icon: '👑',
    desc: 'Play through Queen’s Gambit Accepted or Declined',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 5,
  },
  {
    id: 'op-kings-indian',
    category: 'openings',
    title: 'King’s Indian Rebel',
    icon: '🏹',
    desc: 'Deploy the fierce King’s Indian kingside assault',
    rarity: 'epic',
    xpReward: 65,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 10,
  },
  {
    id: 'op-london-system',
    category: 'openings',
    title: 'London Architect',
    icon: '💂',
    desc: 'Erect the solid London System pyramid',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 3,
  },
  {
    id: 'op-scandi',
    category: 'openings',
    title: 'Scandinavian Raider',
    icon: '⛵',
    desc: 'Strike center early with 1... d5 Scandinavian lines',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 2,
  },
  {
    id: 'op-book-explorer',
    category: 'openings',
    title: 'Theory Connoisseur',
    icon: '📚',
    desc: 'Consult the Opening Book Explorer during your games',
    rarity: 'rare',
    xpReward: 45,
    checkUnlocked: (ctx) => ctx.recentGames.length >= 2,
  },
  {
    id: 'op-scout-intel',
    category: 'openings',
    title: 'Bot Repertoire Scout',
    icon: '🕵️',
    desc: 'Inspect opponent bot opening scouting reports',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.recentGames.length >= 1,
  },
  {
    id: 'op-grand-repertoire',
    category: 'openings',
    title: 'Opening Grandmaster',
    icon: '🎓',
    desc: 'Master both 1. e4 and 1. d4 opening repertoires',
    rarity: 'legendary',
    xpReward: 200,
    checkUnlocked: (ctx) => (ctx.profile?.games_played ?? 0) >= 15 && ctx.adventureHistory.length >= 4,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. STREAKS, DEDICATION & SECRETS ⚡ (20 Achievements)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sec-streak-3',
    category: 'secret',
    title: 'Streak Flame Bearer',
    icon: '🔥',
    desc: 'Maintain a 3-day consecutive training streak',
    rarity: 'common',
    xpReward: 30,
    checkUnlocked: (ctx) => ctx.streakCount >= 3,
  },
  {
    id: 'sec-streak-7',
    category: 'secret',
    title: 'Weekly Champion',
    icon: '⚡',
    desc: 'Hold an unbroken 7-day training streak',
    rarity: 'rare',
    xpReward: 100,
    checkUnlocked: (ctx) => ctx.streakCount >= 7,
  },
  {
    id: 'sec-streak-14',
    category: 'secret',
    title: 'Fortnight Warrior',
    icon: '🌟',
    desc: 'Train consecutively for 14 straight days',
    rarity: 'epic',
    xpReward: 200,
    checkUnlocked: (ctx) => ctx.streakCount >= 14,
  },
  {
    id: 'sec-streak-30',
    category: 'secret',
    title: 'Monthly Legend',
    icon: '💎',
    desc: 'Achieve an astounding 30-day training streak',
    rarity: 'legendary',
    xpReward: 500,
    checkUnlocked: (ctx) => ctx.streakCount >= 30,
  },
  {
    id: 'sec-win-streak-3',
    category: 'secret',
    title: 'Hat Trick',
    icon: '🎩',
    desc: 'Win 3 consecutive bot games in a single session',
    rarity: 'rare',
    xpReward: 60,
    checkUnlocked: (ctx) => (ctx.profile?.win_streak ?? 0) >= 3,
  },
  {
    id: 'sec-win-streak-5',
    category: 'secret',
    title: 'Unstoppable Momentum',
    icon: '🚀',
    desc: 'Win 5 games in a row without a single loss',
    rarity: 'epic',
    xpReward: 150,
    checkUnlocked: (ctx) => (ctx.profile?.win_streak ?? 0) >= 5,
  },
  {
    id: 'sec-win-streak-10',
    category: 'secret',
    title: 'Immortal Streak',
    icon: '🌌',
    desc: 'Achieve a staggering 10-game winning streak',
    rarity: 'legendary',
    xpReward: 400,
    checkUnlocked: (ctx) => (ctx.profile?.highest_win_streak ?? 0) >= 10,
  },
  {
    id: 'sec-speed-demon',
    category: 'secret',
    title: 'Speed Demon',
    icon: '⚡',
    desc: 'Win a bot game in under 2 minutes',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'sec-marathon-win',
    category: 'secret',
    title: 'Marathon Hero',
    icon: '🏃',
    desc: 'Triumph in an epic endgame lasting over 35 moves',
    rarity: 'rare',
    xpReward: 50,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'sec-zero-blunders',
    category: 'secret',
    title: 'Clean Sheet',
    icon: '✨',
    desc: 'Play a full game with zero blunders according to engine analysis',
    rarity: 'epic',
    xpReward: 100,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'sec-comeback',
    category: 'secret',
    title: 'Comeback Kid',
    icon: '🦅',
    desc: 'Rally from a disadvantage to secure a thrilling victory',
    rarity: 'rare',
    xpReward: 75,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'sec-night-owl',
    category: 'secret',
    title: 'Night Owl',
    icon: '🦉',
    desc: 'Train in the Bot Arena late at night',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.recentGames.length >= 1,
  },
  {
    id: 'sec-early-bird',
    category: 'secret',
    title: 'Early Bird',
    icon: '🌅',
    desc: 'Sharpen your tactics with an early morning session',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.recentGames.length >= 1,
  },
  {
    id: 'sec-soundboard-dj',
    category: 'secret',
    title: 'Soundboard Connoisseur',
    icon: '🎧',
    desc: 'Test out different bot personality voice lines and dialogue',
    rarity: 'common',
    xpReward: 20,
    checkUnlocked: (ctx) => true, // Instant discovery easter egg!
  },
  {
    id: 'sec-theme-changer',
    category: 'secret',
    title: 'Board Decorator',
    icon: '🎨',
    desc: 'Customize your board with Wood, Emerald, Slate, or Ice Blue themes',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => true, // Instant discovery easter egg!
  },
  {
    id: 'sec-voice-listener',
    category: 'secret',
    title: 'Attentive Student',
    icon: '🗣️',
    desc: 'Listen to AI Coach voice advice during tactical quests',
    rarity: 'common',
    xpReward: 25,
    checkUnlocked: (ctx) => ctx.quizScore >= 1,
  },
  {
    id: 'sec-pawn-mate',
    category: 'secret',
    title: 'Pawn Checkmate',
    icon: '♟️',
    desc: 'Deliver checkmate with a humble pawn',
    rarity: 'legendary',
    xpReward: 300,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'sec-triple-check',
    category: 'secret',
    title: 'Tactical Precision',
    icon: '🎯',
    desc: 'Deliver 3 consecutive checks leading into checkmate',
    rarity: 'epic',
    xpReward: 120,
    checkUnlocked: (ctx) => ctx.quizScore >= 5,
  },
  {
    id: 'sec-underpromotion',
    category: 'secret',
    title: 'Underpromotion Genius',
    icon: '🐴',
    desc: 'Promote a pawn to a Knight, Rook, or Bishop',
    rarity: 'legendary',
    xpReward: 250,
    checkUnlocked: (ctx) => ctx.recentGames.some((g) => g.result === 'win'),
  },
  {
    id: 'sec-grand-legend',
    category: 'secret',
    title: 'Academy Legend',
    icon: '🌟',
    desc: 'Achieve legendary status across bot battles, puzzles, and streaks',
    rarity: 'legendary',
    xpReward: 1000,
    checkUnlocked: (ctx) =>
      (ctx.profile?.wins ?? 0) >= 5 && ctx.quizScore >= 5 && ctx.streakCount >= 3,
  },
];
