/**
 * Classroom V2 Constants
 */

export const DEFAULT_INITIAL_FEN = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';

export const CLASSROOM_CHANNELS = {
  session: (sessionId: string) => `live-session:${sessionId}`,
  classBroadcast: (classId: string) => `class-roster:${classId}`,
};

export const REALTIME_EVENT_TYPES = {
  SNAPSHOT_RECONCILE: 'SNAPSHOT_RECONCILE',
  BOARD_STATE_UPDATED: 'BOARD_STATE_UPDATED',
  MOVE_PLAYED: 'MOVE_PLAYED',
  PERMISSIONS_CHANGED: 'PERMISSIONS_CHANGED',
  PUZZLE_UPDATED: 'PUZZLE_UPDATED',
  PUZZLE_SOLVED: 'PUZZLE_SOLVED',
  GAME_LOADED: 'GAME_LOADED',
  CURRICULUM_UPDATED: 'CURRICULUM_UPDATED',
  QUIZ_STATE_CHANGED: 'QUIZ_STATE_CHANGED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  PRIVATE_CHAT_MESSAGE: 'PRIVATE_CHAT_MESSAGE',
  STUDENT_RESPONSE: 'STUDENT_RESPONSE',
  RAISE_HAND_CHANGED: 'RAISE_HAND_CHANGED',
  REACTION: 'REACTION',
  PARTICIPANT_PRESENCE_CHANGED: 'PARTICIPANT_PRESENCE_CHANGED',
  BOOKMARK_CREATED: 'BOOKMARK_CREATED',
  CLASS_ENDED: 'CLASS_ENDED',
} as const;

export type RealtimeEventType = (typeof REALTIME_EVENT_TYPES)[keyof typeof REALTIME_EVENT_TYPES];
